name: ProperDuels
main: Chr4st\ProperDuels\ProperDuels
author: Chr4st
version: 1.0.0
api: 4.0.0
description: A duels plugin for PocketMine-MP
permissions:
  properduels.command.arena.create:
    description: Allows the user to create arenas
    default: op
  properduels.command.arena.delete:
    description: Allows the user to delete arenas
    default: op
  properduels.command.arena.list:
    description: Allows the user to list arenas
    default: op
  properduels.command.duel.accept:
    description: Allows the user to accept a duel request
    default: true
  properduels.command.duel.deny:
    description: Allows the user to deny a duel request
    default: true
  properduels.command.duel.leave:
    description: Allows the user to leave a match
    default: true
  properduels.command.duel.queue:
    description: Allows the user to queue a duel
    default: true
  properduels.command.kit.create:
    description: Allows the user to create kits
    default: op
  properduels.command.kit.delete:
    description: Allows the user to delete kits
    default: op
  properduels.command.kit.list:
    description: Allows the user to list kits
    default: op
